= Spring RestClient Benchmark [Groovy]
:toc: left
:sectnums:
:source-highlighter: rouge

// :source-highlighter: highlight.js
// :plantuml: http://localhost:8080/plantuml
// :plantuml-fetch-diagram: true
// :plantuml-size-limit: 8192
// :plantuml: plantuml.com/plantuml
// :diagram-server-url: https://kroki.io/
// :diagram-server-type: kroki_io

++++
<style>
/* CSS block for styling the main content area */
#content {
    max-width: 1140px; /* Set your desired maximum width */
    margin: 0 auto;  /* Center the content */
    padding: 0 1em; /* Add some horizontal padding */
}
/* You can also target other elements like header or footer */
#header, #footer {
    max-width: 1140px; /* Apply the same max-width to header and footer */
    margin: 0 auto;
}
</style>
++++

Filename::
  benchmark_config.json

== Actions

=== Configuration

[%header,cols="1a,4a"]
|===
| id | value
| *description*
| Spring RestClient Benchmark [Groovy]
| *output_filename*
| benchmark_output.json
| *report_filename*
| benchmark_report.html
| *user_class*
| io.tulip.GroovyHttpUser
| *user_params*
|
[%header,cols="1a,3a"]
!===
! id ! value 
! *url* ! http://localhost:7070
! *httpVersion* ! HTTP_1_1
! *connectTimeoutMillis* ! 500
! *readTimeoutMillis* ! 2000
! *debug* ! True
!===
| *user_actions*
|
[%header,cols="2a,2a,4a"]
!===
! id ! value ! description
! *1* ! GET:posts! 
! *2* ! GET:comments! 
! *3* ! GET:todos! 
!===
|===

== Workflows 

[[ApiUser]]
=== ApiUser

[%header,cols="1a,1a"]
|===
| Workflow Diagram | Specification
|[plantuml,wfd0,svg]
----
@startuml
state "-" as A0
state "Action 1" as A1
A1: <GET:posts>

state "Action 2" as A2
A2: <GET:comments>

state "Action 3" as A3
A3: <GET:todos>

A0 --> A1: 0.40
A0 --> A3: 0.60
A1 --> A2: 1.00
A2 --> A0: 1.00
A3 --> A0: 1.00
@enduml
----
| 
[source,json]
----
{
    "-": {
        "1": 0.4, 
        "3": 0.6
    }, 
    "1": {
        "2": 1.0
    }, 
    "2": {
        "-": 1.0
    }, 
    "3": {
        "-": 1.0
    }
}
----
|===

== Contexts

=== Context-1

[%header,cols="1a,2a"]
|===
| id | value 
| *enabled* | True
| *num_users*   | 128
| *num_threads* | 8
|===

== Benchmarks

=== onStart

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *worker_thread_queue_size* | 0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 0
! - 
!===
|===

=== REST1

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 10000.0
| *worker_thread_queue_size* | 0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! - 
!===
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *pre_warmup_duration*
! 30 seconds
! *warmup_duration*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== REST2

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 10000.0
| *worker_thread_queue_size* | 0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! 10 
! 2
! 40 
! 3
! 50 
!===
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *pre_warmup_duration*
! 30 seconds
! *warmup_duration*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== REST3

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 10000.0
| *worker_thread_queue_size* | 0
| *scenario_workflow* | <<ApiUser>>
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *pre_warmup_duration*
! 30 seconds
! *warmup_duration*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== REST3.max

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *worker_thread_queue_size* | 0
| *scenario_workflow* | <<ApiUser>>
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *pre_warmup_duration*
! 30 seconds
! *warmup_duration*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== onStop

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *worker_thread_queue_size* | 0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 100
! - 
!===
|===

== JSON Configuration File

[source,json,linenums]
----
{
    "actions": {
        "description": "Spring RestClient Benchmark [Groovy]", 
        "output_filename": "benchmark_output.json", 
        "report_filename": "benchmark_report.html", 
        "user_class": "io.tulip.GroovyHttpUser", 
        "user_params": {
            "url": "http://localhost:7070", 
            "httpVersion": "HTTP_1_1", 
            "connectTimeoutMillis": 500, 
            "readTimeoutMillis": 2000, 
            "debug": true
        }, 
        "user_actions": {
            "1": "GET:posts", 
            "2": "GET:comments", 
            "3": "GET:todos"
        }
    }, 
    "workflows": {
        "ApiUser": {
            "-": {
                "1": 0.4, 
                "3": 0.6
            }, 
            "1": {
                "2": 1.0
            }, 
            "2": {
                "-": 1.0
            }, 
            "3": {
                "-": 1.0
            }
        }
    }, 
    "benchmarks": {
        "onStart": {
            "save_stats": false, 
            "scenario_actions": [
                {
                    "id": 0
                }
            ]
        }, 
        "REST1": {
            "enabled": true, 
            "aps_rate": 10000.0, 
            "scenario_actions": [
                {
                    "id": 1
                }
            ], 
            "time": {
                "pre_warmup_duration": 30, 
                "warmup_duration": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }
        }, 
        "REST2": {
            "enabled": true, 
            "aps_rate": 10000.0, 
            "scenario_actions": [
                {
                    "id": 1, 
                    "weight": 10
                }, 
                {
                    "id": 2, 
                    "weight": 40
                }, 
                {
                    "id": 3, 
                    "weight": 50
                }
            ], 
            "time": {
                "pre_warmup_duration": 30, 
                "warmup_duration": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }
        }, 
        "REST3": {
            "enabled": true, 
            "aps_rate": 10000.0, 
            "scenario_workflow": "ApiUser", 
            "time": {
                "pre_warmup_duration": 30, 
                "warmup_duration": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }
        }, 
        "REST3.max": {
            "enabled": true, 
            "aps_rate": 0.0, 
            "scenario_workflow": "ApiUser", 
            "time": {
                "pre_warmup_duration": 30, 
                "warmup_duration": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }
        }, 
        "onStop": {
            "save_stats": false, 
            "scenario_actions": [
                {
                    "id": 100
                }
            ]
        }
    }, 
    "contexts": {
        "Context-1": {
            "enabled": true, 
            "num_users": 128, 
            "num_threads": 8
        }
    }
}
----
